-- Storyteller — runtimepath entry.
--
-- Deliberately do not call setup() here. A plugin manager or Nixvim config
-- must call `require("storyteller").setup({...})` so user options are never
-- raced or silently replaced by automatic defaults.
